import { useState } from 'react'
import usePageTitle from '@/hooks/usePageTitle'
import useReceipts from '@/hooks/useReceipts'
import ReceiptPrint from '@/components/accountant/ReceiptPrint'
import Modal from '@/components/ui/Modal'
import { formatCurrency, formatDate } from '@/utils/helpers'

const ReceiptList = () => {
  usePageTitle('Receipts')
  const { receipts } = useReceipts()
  const [selected, setSelected] = useState(null)

  return (
    <div className="space-y-5">
      <div className="rounded-[28px] border p-5" style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}>
        <h1 className="text-2xl font-bold" style={{ color: 'var(--color-text-primary)' }}>Receipts</h1>
      </div>
      <div className="overflow-x-auto rounded-[28px] border" style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}>
        <table className="w-full">
          <thead>
            <tr style={{ borderBottom: '1px solid var(--color-border)' }}>
              {['Receipt No', 'Date', 'Student', 'Class', 'Amount', 'Mode', 'Generated By', 'Actions'].map((head) => (
                <th key={head} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-[0.16em]" style={{ color: 'var(--color-text-muted)' }}>{head}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {receipts.map((receipt) => (
              <tr key={receipt.id} style={{ borderBottom: '1px solid var(--color-border)' }}>
                <td className="px-4 py-3 text-xs font-semibold" style={{ color: '#c2410c' }}>{receipt.receipt_no}</td>
                <td className="px-4 py-3 text-sm" style={{ color: 'var(--color-text-secondary)' }}>{formatDate(receipt.payment_date)}</td>
                <td className="px-4 py-3 text-sm font-semibold" style={{ color: 'var(--color-text-primary)' }}>{receipt.student_name}</td>
                <td className="px-4 py-3 text-sm" style={{ color: 'var(--color-text-secondary)' }}>{receipt.class_name}</td>
                <td className="px-4 py-3 text-sm text-green-700">{formatCurrency(receipt.amount)}</td>
                <td className="px-4 py-3 text-sm capitalize" style={{ color: 'var(--color-text-secondary)' }}>{receipt.payment_mode}</td>
                <td className="px-4 py-3 text-sm" style={{ color: 'var(--color-text-secondary)' }}>{receipt.received_by_name || '--'}</td>
                <td className="px-4 py-3">
                  <button type="button" onClick={() => setSelected(receipt)} className="rounded-full px-3 py-1.5 text-xs font-semibold text-white" style={{ backgroundColor: 'var(--color-brand)' }}>
                    View
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <Modal open={!!selected} onClose={() => setSelected(null)} title="Receipt Preview">
        <ReceiptPrint receipt={selected} />
      </Modal>
    </div>
  )
}

export default ReceiptList
