// src/api/accountantApi.js
import api from './axios'

export const getDashboard                 = ()  => api.get('/accountant/dashboard')
export const getDashboardTodayStats       = ()  => api.get('/accountant/dashboard/today-stats')
export const getDashboardRecentTransactions = (p = {}) => api.get('/accountant/dashboard/recent-transactions', { params: p })
export const getDashboardPendingTasks     = ()  => api.get('/accountant/dashboard/pending-tasks')
export const getDashboardWeekTrend        = ()  => api.get('/accountant/dashboard/week-trend')
export const searchAccountantStudents     = (p) => api.get('/accountant/students/search', { params: p })
export const getStudentPendingInvoices    = (id) => api.get(`/accountant/students/${id}/pending-invoices`)
export const getStudentList       = (p)     => api.get('/accountant/students', { params: p })
export const getStudentFeeDetail  = (id)    => api.get(`/accountant/students/${id}/fees`)
export const getStudentInvoices   = (id)    => api.get(`/accountant/students/${id}/invoices`)
export const getStudentPayments   = (id)    => api.get(`/accountant/students/${id}/payments`)
export const getStudentStatement  = (id)    => api.get(`/accountant/students/${id}/statement/pdf`)
export const collectFee           = (d)     => api.post('/accountant/collect', d)
export const getFeeStructure      = (p)     => api.get('/accountant/fee-structure', { params: p })
export const updateFeeStructure   = (id, d) => api.patch(`/accountant/fee-structure/${id}`, d)
export const createFeeStructure   = (d)     => api.post('/accountant/fee-structure', d)
export const generateFeeInvoices  = (d)     => api.post('/accountant/fee-structure/generate-invoices', d)
export const copyFeeStructureFromSession = (d) => api.post('/accountant/fee-structure/copy-from-session', d)
export const getInvoices         = (p)      => api.get('/accountant/invoices', { params: p })
export const getOverdueInvoices  = (p)      => api.get('/accountant/invoices/overdue', { params: p })
export const getDueTodayInvoices = (p)      => api.get('/accountant/invoices/due-today', { params: p })
export const waiveFee             = (d)     => api.post('/accountant/concessions/apply', d)
export const listReceipts         = (p)     => api.get('/accountant/receipts', { params: p })
export const getReceipt           = (id)    => api.get(`/accountant/receipts/${id}`)
export const getReceiptPdf        = (id)    => api.get(`/accountant/receipts/${id}/pdf`)
export const duplicateReceipt     = (id)    => api.post(`/accountant/receipts/${id}/duplicate`)
export const emailReceipt         = (id)    => api.post(`/accountant/receipts/${id}/email`)
export const whatsappReceipt      = (id)    => api.post(`/accountant/receipts/${id}/whatsapp`)
export const getDefaulters        = (p)     => api.get('/accountant/defaulters', { params: p })
export const sendReminder         = (d)     => api.post('/accountant/defaulters/remind', d)
export const sendBulkReminder     = (d)     => api.post('/accountant/defaulters/remind-bulk', d)
export const getConcessions       = (p)     => api.get('/accountant/concessions', { params: p })
export const getConcessionReport  = (p)     => api.get('/accountant/concessions/report', { params: p })
export const getDailyReport       = (p)     => api.get('/accountant/reports/daily',     { params: p })
export const getMonthlyReport     = (p)     => api.get('/accountant/reports/monthly',   { params: p })
export const getClasswiseReport   = (p)     => api.get('/accountant/reports/classwise', { params: p })
export const getSessionReport     = (p)     => api.get('/accountant/reports/session', { params: p })
export const getDefaultersReport  = (p)     => api.get('/accountant/reports/defaulters',{ params: p })
export const getWaiversReport     = (p)     => api.get('/accountant/reports/concessions',   { params: p })
export const getCustomReport      = (d)     => api.post('/accountant/reports/custom', d)
export const getCarryForwardEligible = (p)  => api.get('/accountant/carry-forward/eligible', { params: p })
export const carryForwardSingle   = (d)     => api.post('/accountant/carry-forward/single', d)
export const carryForwardBulk     = (d)     => api.post('/accountant/carry-forward/bulk', d)
export const getRefunds           = (p)     => api.get('/accountant/refunds', { params: p })
export const processRefund        = (d)     => api.post('/accountant/refunds/process', d)
export const getRefundReport      = (p)     => api.get('/accountant/refunds/report', { params: p })
export const getCheques           = (p)     => api.get('/accountant/cheques', { params: p })
export const getPendingCheques    = (p)     => api.get('/accountant/cheques/pending', { params: p })
export const clearCheque          = (id, d) => api.post(`/accountant/cheques/${id}/clear`, d)
export const bounceCheque         = (id, d) => api.post(`/accountant/cheques/${id}/bounce`, d)
export const getAccountantProfile = ()      => api.get('/accountant/profile')
export const getAccountantProfileActivity = () => api.get('/accountant/profile/activity')
export const changeAccountantPassword = (d) => api.post('/accountant/profile/change-password', d)
