import { useEffect, useMemo, useState } from 'react'
import { Download, Mail, Printer, Search, Send, ShieldCheck } from 'lucide-react'
import * as accountantApi from '@/api/accountantApi'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'
import Select from '@/components/ui/Select'
import TableSkeleton from '@/components/ui/TableSkeleton'
import usePageTitle from '@/hooks/usePageTitle'
import useToast from '@/hooks/useToast'
import { formatCurrency, formatDate } from '@/utils/helpers'
import ReceiptPrint from './ReceiptPrint'
import { AccountantHero, AccountantSection, ExportActions, MetricCard, paymentModeLabel, SummaryTable } from './portalUtils'

export default function ReceiptList() {
  usePageTitle('Receipts')
  const { toastError, toastSuccess } = useToast()
  const [filters, setFilters] = useState({ search: '', from: '', to: '', payment_mode: '' })
  const [items, setItems] = useState([])
  const [loading, setLoading] = useState(true)
  const [preview, setPreview] = useState(null)

  const loadData = () => {
    setLoading(true)
    accountantApi.listReceipts(filters)
      .then((res) => setItems(res.data?.items || []))
      .catch((error) => toastError(error.message || 'Failed to load receipts'))
      .finally(() => setLoading(false))
  }

  useEffect(() => {
    loadData()
  }, [])

  const totals = useMemo(() => items.reduce((acc, item) => {
    acc.amount += Number(item.amount || 0)
    return acc
  }, { amount: 0 }), [items])

  const handleView = async (id) => {
    try {
      const res = await accountantApi.getReceipt(id)
      setPreview(res.data)
    } catch (error) {
      toastError(error.message || 'Receipt not found')
    }
  }

  const handleDuplicate = async (id) => {
    try {
      const res = await accountantApi.duplicateReceipt(id)
      setPreview(res.data)
      toastSuccess('Duplicate receipt generated')
    } catch (error) {
      toastError(error.message || 'Failed to generate duplicate receipt')
    }
  }

  const handleDownload = async (id) => {
    try {
      const res = await accountantApi.getReceiptPdf(id)
      const blob = new Blob([res.data?.html || ''], { type: 'text/html;charset=utf-8' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = res.data?.filename || `receipt-${id}.html`
      document.body.appendChild(link)
      link.click()
      link.remove()
      URL.revokeObjectURL(url)
    } catch (error) {
      toastError(error.message || 'Failed to download receipt')
    }
  }

  const handleEmail = async (id) => {
    try {
      await accountantApi.emailReceipt(id)
      toastSuccess('Receipt email queued')
    } catch (error) {
      toastError(error.message || 'Unable to queue email')
    }
  }

  const handleWhatsApp = async (id) => {
    try {
      await accountantApi.whatsappReceipt(id)
      toastSuccess('WhatsApp receipt queued')
    } catch (error) {
      toastError(error.message || 'Unable to queue WhatsApp')
    }
  }

  const columns = [
    { key: 'receipt_no', label: 'Receipt No' },
    { key: 'date', label: 'Date', render: (row) => formatDate(row.date) },
    { key: 'created_at', label: 'Time', render: (row) => new Date(row.created_at).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) },
    { key: 'student_name', label: 'Student' },
    { key: 'class_name', label: 'Class' },
    { key: 'amount', label: 'Amount', render: (row) => formatCurrency(row.amount) },
    { key: 'payment_mode_display', label: 'Mode', render: (row) => paymentModeLabel(row.payment_mode_display) },
    { key: 'generated_by', label: 'Generated By' },
    {
      key   : 'actions',
      label : 'Actions',
      render: (row) => (
        <div className="flex flex-wrap gap-2">
          <Button size="sm" variant="secondary" onClick={() => handleView(row.id)}>View</Button>
          <Button size="sm" variant="secondary" onClick={() => handleDownload(row.id)} icon={Download}>Download</Button>
          <Button size="sm" variant="secondary" onClick={() => handleEmail(row.id)} icon={Mail}>Email</Button>
          <Button size="sm" variant="secondary" onClick={() => handleWhatsApp(row.id)} icon={Send}>WhatsApp</Button>
          <Button size="sm" variant="outline" onClick={() => handleDuplicate(row.id)} icon={ShieldCheck}>Duplicate</Button>
        </div>
      ),
      csv: () => '',
    },
  ]

  return (
    <div className="space-y-6">
      <AccountantHero
        eyebrow="Step 9"
        title="Receipt Management"
        description="Search receipts fast by receipt number, student, date, or payment mode, then preview, print, download, email, or issue a logged duplicate."
        actions={<ExportActions filename="receipt-summary.csv" columns={columns.slice(0, 8)} rows={items} printTitle="Receipt Summary" />}
      />
      <div className="grid gap-4 md:grid-cols-2">
        <MetricCard label="Receipts Found" value={items.length} />
        <MetricCard label="Receipt Amount Total" value={formatCurrency(totals.amount)} accent="#15803d" />
      </div>
      <AccountantSection title="Search Receipts" subtitle="Fast search by receipt number, student, date range, amount, or mode.">
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
          <Input label="Search" placeholder="Receipt number or student" value={filters.search} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} />
          <Input label="From Date" type="date" value={filters.from} onChange={(event) => setFilters((current) => ({ ...current, from: event.target.value }))} />
          <Input label="To Date" type="date" value={filters.to} onChange={(event) => setFilters((current) => ({ ...current, to: event.target.value }))} />
          <Select
            label="Payment Mode"
            value={filters.payment_mode}
            onChange={(event) => setFilters((current) => ({ ...current, payment_mode: event.target.value }))}
            options={[
              { value: 'cash', label: 'Cash' },
              { value: 'online', label: 'Online' },
              { value: 'upi', label: 'UPI' },
              { value: 'cheque', label: 'Cheque' },
              { value: 'dd', label: 'DD' },
            ]}
          />
          <div className="flex items-end gap-3">
            <Button icon={Search} onClick={loadData}>Search</Button>
            <Button variant="secondary" onClick={() => { setFilters({ search: '', from: '', to: '', payment_mode: '' }); setTimeout(loadData, 0) }}>Reset</Button>
          </div>
        </div>
      </AccountantSection>
      <AccountantSection title="Receipt Table" subtitle="Every row can open a printable preview.">
        {loading ? <TableSkeleton cols={9} rows={8} /> : <SummaryTable columns={columns} rows={items} emptyTitle="No receipts found" emptyDescription="Try a broader date range or search term." />}
      </AccountantSection>
      {preview ? <ReceiptPrint receipt={preview} onClose={() => setPreview(null)} /> : null}
    </div>
  )
}
